config/routes.rb
Rails.application.routes.draw do
  resources :welcomes

  resources :appointments

  resources :patients

  resources :invoices

  resources :physicians

  resources :diagnostic_codes

   root 'welcomes#index'

  get 'about' => 'welcomes#about'
  get 'news' => 'welcomes#news'
  get 'administrator' => 'welcomes#administrator'
  get 'officeworker' => 'welcomes#officeworker'
  get '/appointment-hours' => 'appointments#getHours'

end

app/models/diagnostic_code.rb
class DiagnosticCode < ActiveRecord::Base
  validates :code, presence: true, uniqueness: true
  validates :description, :price, presence: true
end

app/controllers/diagnostic_codes_controller.rb
class DiagnosticCodesController < ApplicationController
  before_action :set_diagnostic_code, only: [:show, :edit, :update, :destroy]

  # GET /diagnostic_codes
  # GET /diagnostic_codes.json
  def index
    @diagnostic_codes = DiagnosticCode.all
  end

  # GET /diagnostic_codes/1
  # GET /diagnostic_codes/1.json
  def show
  end

  # GET /diagnostic_codes/new
  def new
    @diagnostic_code = DiagnosticCode.new
  end

  # GET /diagnostic_codes/1/edit
  def edit
  end

  # POST /diagnostic_codes
  # POST /diagnostic_codes.json
  def create
    @diagnostic_code = DiagnosticCode.new(diagnostic_code_params)

    respond_to do |format|
      if @diagnostic_code.save
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully created.' }
        format.json { render :show, status: :created, location: @diagnostic_code }
      else
        format.html { render :new }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnostic_codes/1
  # PATCH/PUT /diagnostic_codes/1.json
  def update
    respond_to do |format|
      if @diagnostic_code.update(diagnostic_code_params)
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagnostic_code }
      else
        format.html { render :edit }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_codes/1
  # DELETE /diagnostic_codes/1.json
  def destroy
    @diagnostic_code.destroy
    respond_to do |format|
      format.html { redirect_to diagnostic_codes_url, notice: 'Diagnostic code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostic_code
      @diagnostic_code = DiagnosticCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnostic_code_params
      params.require(:diagnostic_code).permit(:code, :description, :price)
    end
end

app/helpers/diagnostic_codes_helper.rb
module DiagnosticCodesHelper
end

app/views/diagnostic_codes/_form.html.erb
<%= form_for @diagnostic_code, :html => { :class => "form-horizontal diagnostic_code" } do |f| %>

    <% if @diagnostic_code.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@diagnostic_code.errors.count, "error") %> prohibited this diagnostic_code from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @diagnostic_code.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'form-control' %>
    </div>
    <%= error_span(@diagnostic_code[:code]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@diagnostic_code[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%= error_span(@diagnostic_code[:price]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            diagnostic_codes_path, :class => 'btn btn-default' %>

<% end %>

app/views/diagnostic_codes/edit.html.erb
<%- model_class = DiagnosticCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diagnostic_codes/index.html.erb
<%- model_class = DiagnosticCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @diagnostic_codes.each do |diagnostic_code| %>
      <tr>
        <td><%= link_to diagnostic_code.id, diagnostic_code_path(diagnostic_code) %></td>
        <td><%= diagnostic_code.code %></td>
        <td><%= diagnostic_code.description %></td>
        <td><%= diagnostic_code.price %></td>
        <td><%=l diagnostic_code.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_diagnostic_code_path(diagnostic_code), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      diagnostic_code_path(diagnostic_code),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_diagnostic_code_path,
            :class => 'btn btn-primary' %>

app/views/diagnostic_codes/new.html.erb
<%- model_class = DiagnosticCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diagnostic_codes/show.html.erb
<%- model_class = DiagnosticCode -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @diagnostic_code.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @diagnostic_code.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @diagnostic_code.price %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              diagnostic_codes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_diagnostic_code_path(@diagnostic_code), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              diagnostic_code_path(@diagnostic_code),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>