config/routes.rb
Rails.application.routes.draw do
  resources :welcomes

  resources :appointments

  resources :patients

  resources :invoices

  resources :physicians

  resources :diagnostic_codes

   root 'welcomes#index'

  get 'about' => 'welcomes#about'
  get 'news' => 'welcomes#news'
  get 'administrator' => 'welcomes#administrator'
  get 'officeworker' => 'welcomes#officeworker'
  get '/appointment-hours' => 'appointments#getHours'

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  def about
  end

  def news
  end

  def administrator
    @physicians = Physician.all
    @physician = Physician.new
    @appointments = Appointment.all
    @diagnostic_code = DiagnosticCode.new
    @diagnostic_codes = DiagnosticCode.all
    @invoices = Invoice.all
  end

  def officeworker
    @invoice = Invoice.new
    @invoices = Invoice.all
    query = Appointment.where("date <'"+Time.zone.now.to_s+"'") #find all past appointments
    invoiced_appointment_ids = ''
    imax = query.count
    i =0
    query.each do |appointment|
      if !Invoice.find_by_appointmentId(appointment.id).nil? # only select the appointments that have not been invoiced
        invoiced_appointment_ids += 'id != '+ appointment.id.to_s
        if i < imax
          invoiced_appointment_ids += ' and '
          i +=1
        end
      else
        imax-=1
      end
    end
    if invoiced_appointment_ids.last(5) == ' and ';invoiced_appointment_ids=invoiced_appointment_ids[0..-5]  end
    @invoices_pending = query.where(invoiced_appointment_ids) #complete query
  end



  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.require(:welcome).permit(:index)
    end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_form_invoices_pending.html.erb
<%if @invoices_pending.any? %>
    <% @invoices_pending.each do |appointment|%>

        <%= form_for @invoice, remote: true, :html => { :'data-type' => 'json', :class => "dl-horizontal breadcrumb", :id =>"appointments-pending-invoicing"} do |f| %>
            <% if appointment.errors.any? %>
                <div id="error_expl" class="panel panel-danger">
                  <div class="panel-heading">
                    <h3 class="panel-title"><%= pluralize(appointment.errors.count, "error") %> prohibited this patient from being saved:</h3>
                  </div>
                  <div class="panel-body">
                    <ul>
                      <% @patient.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                      <% end %>
                    </ul>
                  </div>
                </div>
            <% end %>
            <div >
              <%= f.submit nil,:class => 'btn btn-default pull-right', :type => ''%>
              <dl>
                <dt><strong>Appointment #:</strong></dt>
                <dd><%= appointment.id %></dd>
                <dt><strong>Date:</strong></dt>
                <dd><%=l appointment.date %></dd>
                <dt><strong>Patient Name:</strong></dt>
                <% Patient.where(:Id => appointment.patientId).each do |patient|%>
                    <dd><%= patient.name  %></dd>
                <%end%>
                <dt><strong>Physician Name:</strong></dt>
                <% Physician.where(:Id => appointment.physicianId).each do |physician|%>
                    <dd><%= physician.name  %></dd>
                <%end%>
                <dt><strong>Diagnostic:</strong></dt>
                <% DiagnosticCode.where(:Id => appointment.diagnosticCodeId).each do |diagnostic|%>
                    <dd><%= diagnostic.description  %></dd>
                <%end%>
                <dt><strong>Estimated Price:</strong></dt>
              </dl>
              <% DiagnosticCode.where(:Id => appointment.diagnosticCodeId).each do |diagnostic|%>
                  <dd>$<%= diagnostic.price%></dd>
                  <%= f.hidden_field :subtotal, :value => diagnostic.price%>
              <%end%>
              <%= f.hidden_field :patientId, :value => appointment.patientId%>
              <%= f.hidden_field :appointmentId, :value => appointment.id%>
              <br>

            </div>

        <%end%>


    <%end%>
<%else%>
    <div id="appointments-pending-invoicing">
    <p>There are no appointments pending invoicing.</p>
    </div>
<%end%>

<script>
    $(document).on("click", "#appointments-pending-invoicing > div > input.btn",function(){
        $(this).attr("value","Processing");
        //$(this).attr("type","submit");
        //callback handler for form submit
        $(this<"div < #appointments-pending-invoicing").submit(function(e)
        {
            var postData = $(this).serializeArray();
            var formURL = $(this).attr("action");
            $.ajax(
                    {
                        url : formURL,
                        type: "POST",
                        data : postData,
                        success:function()
                        {
                            //data: return data from server
                            //alert("Success");
                            //$(this>"div > input.btn.pull-right").attr("class","btn btn-success pull-right");
                            //$(this>"div > input.btn.pull-right").attr("value","Invoice created");

                        },
                        error: function(jqXHR, textStatus, errorThrown)
                        {
                            //if fails
                            //alert("Failed");
                            $(this>"div > input.btn.pull-right").attr("class","btn btn-warning pull-right");
                            $(this>"div > input.btn.pull-right").attr("value","Failed");
                        }
                    });
            e.preventDefault(); //STOP default action
            e.unbind(); //unbind. to stop multiple form submit.
        });

        $(this).submit(); //Submit  the FORM
        $(this).attr("class","btn btn-success pull-right");
        $(this).attr("value","Invoice created").delay(2000);
        $(this<"div < #appointments-pending-invoicing").remove();
        $("#collapseOne > div").load("/officeworker.html #appointments-pending-invoicing");
        $("#collapseTwo").load("/officeworker.html #collapseTwo > div");
    });
</script>

app/views/welcomes/about.html.erb
<h3 class="page-header">About</h3>
<p>DermaLab id the result of the union of a group of three University of Houston gratuates, established in 1994.</p>

app/views/welcomes/administrator.html.erb
<h3 class="page-header">Administrator</h3>

<div class="panel-group" id="accordion">
  <div class="panel panel-default" id="panel1">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseOne"
         href="#">
      <h4  class="panel-title">Report</h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">

        <% @physicians.each do |physician| %>

            <div class="panel panel-default" id="panel1">
              <div class="panel-heading" data-toggle="collapse" data-target="#collapse_physician<%= physician.id %>"
                   href="#">
                <%= physician.name %>
              </div>
              <div id="collapse_physician<%= physician.id %>" class="panel-collapse collapse">
                <div class="panel-body">

                  <% if @appointments.where(:physicianId => physician.id).where("date < '"+ Time.zone.now.to_s+ "'").any?  %>

                      <table class="table table-striped table-condensed">
                        <thead>
                        <tr>
                          <th>Appointment Date:</th>
                          <th>Amount Invoiced:</th>
                        </tr>
                        </thead>
                        <tbody><% @appointments.where(:physicianId => physician.id).where("date < '"+ Time.zone.now.to_s+ "'").each do |appointment| %>
                            <tr>
                              <td>
                                <%= link_to appointment.date.strftime('%c'), appointment_path(appointment)%>
                              </td>
                              <% if !@invoices.where(:appointmentId => appointment.id).empty? %>
                                  <% @invoices.where(:appointmentId => appointment.id).each do |invoice| %>
                                      <td><%= if invoice.subtotal.nil?; html_escape 'Amount not defined.'; else link_to number_to_currency(invoice.subtotal), invoice_path(invoice) end%></td>
                                  <%end%>
                              <%else%> <td>Invoice not found.</td> <%end%>
                            </tr><%end%>
                        </tbody>
                      </table>
                  <% else%> No records found.
                  <%end%>



                </div>
              </div>
            </div>


        <%end%>




      </div>
    </div>
  </div>
  <div class="panel panel-default" id="panel2">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseTwo"
         href="#">
      <h4 class="panel-title">
        Physicians
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">

        <%= render :template => 'physicians/index'%>

      </div>
    </div>
  </div>
  <div class="panel panel-default" id="panel3">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseThree"
         href="#collapseThree" class="collapsed">
      <h4 class="panel-title">
        Diagnostic Codes
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">

        <%= render :template => 'diagnostic_codes/index'%>

        <script>$("div.page-header").remove();</script>

      </div>
    </div>
  </div>
</div>

app/views/welcomes/index.html.erb
<h3 class="page-header">Welcome to DermaLab!</h3><br>
<p>DermaLab is the leader in treating skin anomalies.</p>
<p>Say goodbye to acne, fungi and any other stain! We will take care of you.</p>

app/views/welcomes/news.html.erb
<h3 class="page-header">News</h3>

<p>There are no news to present at the moment.</p>


app/views/welcomes/officeworker.html.erb
<h3 class="page-header">Office Worker</h3>


<div class="panel-group" id="accordion">
  <div class="panel panel-default" id="panel1">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseOne"
         href="#">
      <h4  class="panel-title">Appointments Pending Invoicing</h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">

        <%= render :partial => 'form_invoices_pending'%>



      </div>
    </div>
  </div>
  <div class="panel panel-default" id="panel2">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseTwo"
         href="#">
      <h4 class="panel-title">
        Invoices Archive
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">

        <%= render :template => 'invoices/index' %>
        <script>$("div.page-header").remove();</script>

      </div>
    </div>
  </div>
</div>
