config/routes.rb
Rails.application.routes.draw do
  resources :welcomes

  resources :appointments

  resources :patients

  resources :invoices

  resources :physicians

  resources :diagnostic_codes

   root 'welcomes#index'

  get 'about' => 'welcomes#about'
  get 'news' => 'welcomes#news'
  get 'administrator' => 'welcomes#administrator'
  get 'officeworker' => 'welcomes#officeworker'
  get '/appointment-hours' => 'appointments#getHours'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments, :foreign_key => :patientId
  has_many :physicians, :through => :appointments


  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @appointments = Appointment.new
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :email)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for @patient, :html => { :class => "form-horizontal patient" } do |f| %>

    <% if @patient.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @patient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@patient[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%= error_span(@patient[:email]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            patients_path, :class => 'btn btn-default' %>

<% end %>

app/views/patients/edit.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/patients/index.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to patient.id, patient_path(patient) %></td>
        <td><%= patient.name %></td>
        <td><%= patient.email %></td>
        <td><%=l patient.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_patient_path(patient), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      patient_path(patient),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_patient_path,
            :class => 'btn btn-primary' %>

app/views/patients/new.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/patients/show.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @patient.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @patient.email %></dd>
</dl>

<div class="panel-group" id="accordion">
  <div class="panel panel-default" id="panel1">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseOne"
         href="#">
      <h4  class="panel-title">Future Appointments</h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">

        <%if @patient.appointments.where("date > '"+ Time.zone.now.to_s+ "'").any? %>
            <% @patient.appointments.where("date > '"+ Time.zone.now.to_s+ "'").each do |appointment|%>
                    <dl class="dl-horizontal breadcrumb" href="<% appointment_path(appointment) %>">
                      <dt><strong>Date:</strong></dt>
                      <dd><%= appointment.date.strftime('%c') %></dd>
                      <dt><strong>Physician Name:</strong></dt>
                      <% Physician.where(:id => appointment.physicianId).each do |physician|%>
                      <dd><%= physician.name  %></dd>
                      <%end%>
                      <dt><strong>Patient Concern:</strong></dt>
                      <dd><%= appointment.patientConcern %>
                      <%= button_to 'Cancel Appointment',appointment_path(appointment), :method=> 'delete',:data => {:confirm => 'Are you sure?'},:class => 'btn btn-xs btn-danger pull-right'%></dd>
                    </dl>
                <%end%>
            <%else%>
        <p>There are no future appointments.</p>
        <%end%>
      </div>
    </div>
  </div>
  <div class="panel panel-default" id="panel2">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseTwo"
         href="#">
      <h4 class="panel-title">
        Past Appointments
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <%if @patient.appointments.where("date < '"+ Time.zone.now.to_s+ "'").any? %>
            <% @patient.appointments.where("date < '"+ Time.zone.now.to_s+ "'").each do |appointment|%>
                <dl class="dl-horizontal breadcrumb">
                  <dt><strong>Date:</strong></dt>
                  <dd><%= appointment.date.strftime('%c') %></dd>
                  <dt><strong>Physician Name:</strong></dt>
                  <% Physician.where(:id => appointment.physicianId).each do |physician|%>
                  <dd><%= physician.name  %></dd>
                      <%end%>
                  <dt><strong>Your Concern:</strong></dt>
                  <dd><%= appointment.patientConcern %></dd>
                  <dt><strong>Physician Notes:</strong></dt>
                  <dd><%= appointment.physicianNotes %></dd>
                  <dt><strong>Diagnostic:</strong></dt>
                  <dd><% DiagnosticCode.find(appointment.diagnosticCodeId) do |diagnostic| %><%= diagnostic.code+ ' - '+ diagnostic.description%><% end%></dd>
                </dl>
                <%end%>
        <%else%>
            <p>There are no past appointments.</p>
        <%end%>
      </div>
    </div>
  </div>
  <div class="panel panel-default" id="panel3">
    <div class="panel-heading" data-toggle="collapse" data-target="#collapseThree"
         href="#collapseThree" class="collapsed">
      <h4 class="panel-title">
          New appointment
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        <%= render :partial => 'appointments/form', object:  @appointment = Appointment.new(:patientId => @patient.id), remote: true %>
        <script>
            $("#p_notes-div").remove();
            $("#d_code-div").remove();
            $("#appointment_patientId option:not(:selected)").remove();
        </script>
      </div>
    </div>
  </div>
</div>



<%= link_to t('.back', :default => t("helpers.links.back")),
              patients_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_patient_path(@patient), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              patient_path(@patient),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>